# V29: Natural Spline Basis Properties
#
# Validates mathematical properties of the Harrell RCS basis functions
# generated by .emulate_rcs_basis() and .emulate_compute_knots().
# These must be correct for tte_fit and tte_predict to work.

# ---------------------------------------------------------------------------
# Test 1: Basis matrix has correct dimensions (n x df)
# ---------------------------------------------------------------------------
test_that("V29-1: RCS basis matrix dimensions match df", {
  skip_on_cran()

  x <- seq(0, 10, length.out = 100)

  for (df in 2:5) {
    knots <- emulate:::.emulate_compute_knots(x, df)
    basis <- emulate:::.emulate_rcs_basis(x, knots, df)

    expect_equal(nrow(basis), length(x),
      label = paste("basis rows = length(x) for df =", df))
    expect_equal(ncol(basis), df,
      label = paste("basis cols = df for df =", df))
  }
})

# ---------------------------------------------------------------------------
# Test 2: First basis column is the identity (linear term)
# ---------------------------------------------------------------------------
test_that("V29-2: first basis column equals x (linear term)", {
  skip_on_cran()

  x <- seq(0, 20, length.out = 200)

  for (df in 2:4) {
    knots <- emulate:::.emulate_compute_knots(x, df)
    basis <- emulate:::.emulate_rcs_basis(x, knots, df)

    expect_equal(basis[, 1], x, tolerance = 1e-12,
      label = paste("first column is x for df =", df))
  }
})

# ---------------------------------------------------------------------------
# Test 3: Number of knots = df + 1
# ---------------------------------------------------------------------------
test_that("V29-3: compute_knots returns df+1 knots with boundary at min/max", {
  skip_on_cran()

  x <- c(1, 3, 5, 7, 9, 11, 13, 15, 17, 19)

  for (df in 1:5) {
    knots <- emulate:::.emulate_compute_knots(x, df)

    expect_equal(length(knots), df + 1,
      label = paste("n_knots = df+1 for df =", df))
    expect_equal(knots[1], min(x),
      label = paste("first knot = min(x) for df =", df))
    expect_equal(knots[length(knots)], max(x),
      label = paste("last knot = max(x) for df =", df))
  }
})

# ---------------------------------------------------------------------------
# Test 4: Basis is continuous (no jumps at knots)
# ---------------------------------------------------------------------------
test_that("V29-4: RCS basis is continuous at internal knots", {
  skip_on_cran()

  x_dense <- seq(0, 20, length.out = 10000)
  df <- 4
  knots <- emulate:::.emulate_compute_knots(x_dense, df)
  basis <- emulate:::.emulate_rcs_basis(x_dense, knots, df)

  # Check continuity: max absolute difference between adjacent values
  # should be small (proportional to step size)
  step <- x_dense[2] - x_dense[1]
  for (j in seq_len(ncol(basis))) {
    max_jump <- max(abs(diff(basis[, j])))
    # Max jump should be proportional to step size (no discontinuities)
    # Allow generous bound: max_jump < 100 * step (smooth function)
    expect_lt(max_jump, 100 * step,
      label = paste("column", j, "is continuous"))
  }
})

# ---------------------------------------------------------------------------
# Test 5: RCS basis is linear beyond boundary knots
# ---------------------------------------------------------------------------
test_that("V29-5: RCS basis is linear beyond boundary knots", {
  skip_on_cran()

  # Generate data concentrated in [5, 15], test linearity beyond boundaries
  x_interior <- seq(5, 15, length.out = 500)
  df <- 3
  knots <- emulate:::.emulate_compute_knots(x_interior, df)

  # Evaluate at points BEYOND the boundary knots
  x_beyond <- seq(knots[length(knots)], knots[length(knots)] + 10,
                   length.out = 100)
  basis_beyond <- emulate:::.emulate_rcs_basis(x_beyond, knots, df)

  # For RCS, nonlinear columns (2+) should be linear beyond boundaries
  # Second differences should be ~0
  for (j in 2:ncol(basis_beyond)) {
    second_diff <- diff(diff(basis_beyond[, j]))
    max_nonlin <- max(abs(second_diff))
    expect_lt(max_nonlin, 1e-6,
      label = paste("column", j, "is linear beyond upper boundary"))
  }
})

# ---------------------------------------------------------------------------
# Test 6: Basis at df=1 is just the variable itself
# ---------------------------------------------------------------------------
test_that("V29-6: df=1 produces single linear column", {
  skip_on_cran()

  x <- seq(0, 10, length.out = 50)
  knots <- emulate:::.emulate_compute_knots(x, 1)
  basis <- emulate:::.emulate_rcs_basis(x, knots, 1)

  expect_equal(ncol(basis), 1)
  expect_equal(basis[, 1], x, tolerance = 1e-12)
})

# ---------------------------------------------------------------------------
# Test 7: Spline basis matches Stata output on shared data
# ---------------------------------------------------------------------------
test_that("V29-7: knot positions use quantile type=2 (Stata compatible)", {
  skip_on_cran()

  # Known data: integers 0 to 19
  x <- 0:19

  # df=3: 2 internal knots at quantiles 1/3 and 2/3
  knots <- emulate:::.emulate_compute_knots(x, 3)

  # quantile(0:19, c(1/3, 2/3), type=2) should give specific values
  expected_internal <- quantile(x, c(1/3, 2/3), type = 2)
  expect_equal(knots[2], unname(expected_internal[1]), tolerance = 1e-10,
    label = "internal knot 1 matches quantile type=2")
  expect_equal(knots[3], unname(expected_internal[2]), tolerance = 1e-10,
    label = "internal knot 2 matches quantile type=2")
})
