#' Prepare data for target trial emulation
#'
#' This is the first step in the TTE pipeline. It maps your variable names to
#' the internal naming convention, validates that the data is in proper
#' person-period format, computes summary statistics, and returns a \code{emulate}
#' object that carries the data and settings through all subsequent steps.
#'
#' @section Person-period data format:
#' The input data must be in \strong{long format} with exactly one row per
#' individual per time period. For example, if patient 1 is observed over
#' periods 0 through 9, there should be exactly 10 rows for that patient.
#' The period variable must be integer-valued (0, 1, 2, ...) and typically
#' starts at 0 or 1. There must be no duplicate \code{(id, period)}
#' combinations.
#'
#' @section Estimands:
#' The \code{estimand} argument determines the causal question being asked
#' and controls how the data will be processed in subsequent pipeline steps:
#' \describe{
#'   \item{\strong{"ITT"} (Intention-to-Treat)}{Compares groups as originally
#'     assigned at baseline, regardless of whether they actually adhered to
#'     treatment. In the expansion step, no cloning occurs and no artificial
#'     censoring is applied. No inverse probability weights are needed. This
#'     is the simplest estimand but may be biased in the presence of treatment
#'     switching.}
#'   \item{\strong{"PP"} (Per-Protocol)}{Compares groups who adhered to their
#'     assigned treatment strategy. In the expansion step, individuals are
#'     cloned into treatment and control arms. Clones are artificially
#'     censored when they deviate from their assigned strategy, and inverse
#'     probability weights correct for the selection bias introduced by this
#'     censoring. This is the default estimand.}
#'   \item{\strong{"AT"} (As-Treated)}{Compares groups based on the treatment
#'     they actually received over time. Uses the same clone-censor-weight
#'     machinery as PP but defines deviation differently.}
#' }
#'
#' @param data A \code{data.frame} or \code{data.table} in person-period
#'   (long) format. Must contain at least the columns named by \code{id},
#'   \code{period}, \code{treatment}, \code{outcome}, and \code{eligible}.
#'   The data is copied internally, so the original object is never modified.
#' @param id A single character string giving the name of the column that
#'   uniquely identifies each individual (e.g., \code{"patient_id"}).
#' @param period A single character string giving the name of the column
#'   containing the time period. Must be integer-valued (0, 1, 2, ...).
#' @param treatment A single character string giving the name of the binary
#'   treatment variable. Must contain only 0 and 1 (and optionally \code{NA}).
#'   A value of 1 means the individual is receiving treatment at that period.
#' @param outcome A single character string giving the name of the binary
#'   outcome variable. Must contain only 0 and 1. A value of 1 means the
#'   outcome event occurred at that period. The outcome is assumed to be
#'   terminal (no rows should exist after the event).
#' @param eligible A single character string giving the name of the binary
#'   eligibility variable. Must contain only 0 and 1. A value of 1 means the
#'   individual is eligible to enter a new trial at that period. Only periods
#'   where \code{eligible = 1} will be used as trial start times in
#'   \code{\link{emulate_expand}}.
#' @param censor An optional character string giving the name of a binary
#'   censoring indicator (0/1). A value of 1 means the individual is censored
#'   (e.g., lost to follow-up) at that period. If \code{NULL} (the default),
#'   no external censoring variable is used.
#' @param covariates An optional character vector of column names for
#'   \strong{time-varying covariates}. These variables may change value across
#'   periods and will be used in weighting models. During expansion, their
#'   values are frozen at trial baseline.
#' @param baseline_covariates An optional character vector of column names for
#'   \strong{baseline-only covariates}. These are variables that do not change
#'   over time (e.g., sex, birth year). They are included in the analysis
#'   alongside time-varying covariates.
#' @param estimand A character string specifying the causal estimand. Must be
#'   one of \code{"ITT"} (intention-to-treat), \code{"PP"} (per-protocol), or
#'   \code{"AT"} (as-treated). Default is \code{"PP"}. Case-insensitive.
#' @param prefix A character string used as a prefix for all variables
#'   generated by the pipeline (e.g., follow-up time, trial indicator, arm
#'   indicator). Default is \code{"_emulate_"}. You generally do not need to
#'   change this unless it conflicts with existing column names in your data.
#'
#' @return A \code{emulate} object (see \code{\link{new_emulate}} for structure
#'   details) with the pipeline state set to \code{prepared = TRUE}. The
#'   object is returned invisibly and a summary of the prepared data is
#'   printed via \code{message()}.
#'
#' @seealso \code{\link{emulate_validate}} for the next pipeline step,
#'   \code{\link{emulate_expand}} for trial expansion.
#'
#' @references
#' Hernan MA, Robins JM (2016). "Using Big Data to Emulate a Target Trial
#' When a Randomized Trial Is Not Available." \emph{American Journal of
#' Epidemiology}, 183(8), 758-764.
#'
#' @examples
#' # Create a small person-period dataset
#' set.seed(42)
#' n_ids <- 20
#' n_periods <- 8
#' dat <- data.frame(
#'   id = rep(seq_len(n_ids), each = n_periods),
#'   period = rep(0:(n_periods - 1), times = n_ids),
#'   treatment = 0L,
#'   outcome = 0L,
#'   eligible = 1L,
#'   age = rep(sample(40:70, n_ids, replace = TRUE), each = n_periods),
#'   sex = rep(sample(0:1, n_ids, replace = TRUE), each = n_periods)
#' )
#' # Simulate some treatment initiation
#' dat$treatment <- ifelse(dat$period >= sample(2:6, nrow(dat), replace = TRUE), 1L, 0L)
#' # Simulate a few events
#' dat$outcome[sample(which(dat$period > 3), 5)] <- 1L
#'
#' # Prepare the data for a per-protocol analysis
#' obj <- emulate_prepare(
#'   data = dat,
#'   id = "id",
#'   period = "period",
#'   treatment = "treatment",
#'   outcome = "outcome",
#'   eligible = "eligible",
#'   covariates = "age",
#'   baseline_covariates = "sex",
#'   estimand = "PP"
#' )
#' print(obj)
#'
#' @export
emulate_prepare <- function(data, id, period, treatment, outcome, eligible,
                        censor = NULL, covariates = NULL,
                        baseline_covariates = NULL,
                        estimand = "PP", prefix = "_emulate_") {

  # Convert to data.table (copy to avoid modifying user's data)
  dt <- data.table::as.data.table(data)

  # Validate estimand
  estimand <- toupper(estimand)
  if (!estimand %in% c("ITT", "PP", "AT")) {
    stop("estimand must be 'ITT', 'PP', or 'AT'", call. = FALSE)
  }

  # Check required columns exist
  required <- c(id, period, treatment, outcome, eligible)
  missing_cols <- setdiff(required, names(dt))
  if (length(missing_cols) > 0) {
    stop("Missing columns: ", paste(missing_cols, collapse = ", "), call. = FALSE)
  }

  if (!is.null(censor) && !censor %in% names(dt)) {
    stop("Censor variable '", censor, "' not found in data", call. = FALSE)
  }

  optional <- c(covariates, baseline_covariates)
  if (length(optional) > 0) {
    missing_opt <- setdiff(optional, names(dt))
    if (length(missing_opt) > 0) {
      stop("Missing covariate columns: ", paste(missing_opt, collapse = ", "),
           call. = FALSE)
    }
  }

  # Validate period is integer-valued
  p <- dt[[period]]
  if (any(p != floor(p), na.rm = TRUE)) {
    stop("Period variable '", period, "' must be integer-valued", call. = FALSE)
  }

  # Validate binary variables
  for (v in c(treatment, outcome, eligible)) {
    vals <- dt[[v]]
    if (any(!vals %in% c(0L, 1L, NA), na.rm = FALSE)) {
      # Allow numeric 0/1 too
      non_binary <- vals[!is.na(vals) & !vals %in% c(0, 1)]
      if (length(non_binary) > 0) {
        stop("Variable '", v, "' must be binary (0/1)", call. = FALSE)
      }
    }
  }

  if (!is.null(censor)) {
    vals <- dt[[censor]]
    non_binary <- vals[!is.na(vals) & !vals %in% c(0, 1)]
    if (length(non_binary) > 0) {
      stop("Censor variable '", censor, "' must be binary (0/1)", call. = FALSE)
    }
  }

  # Check person-period: one row per (id, period)
  dup_count <- dt[, .N, by = c(id, period)][N > 1]
  if (nrow(dup_count) > 0) {
    stop("Data is not in person-period format: ",
         nrow(dup_count), " duplicate (id, period) combinations", call. = FALSE)
  }

  # Compute summary statistics
  n_obs <- nrow(dt)
  n_ids <- data.table::uniqueN(dt[[id]])
  period_range <- range(dt[[period]], na.rm = TRUE)
  n_eligible <- sum(dt[[eligible]] == 1, na.rm = TRUE)
  n_events <- sum(dt[[outcome]] == 1, na.rm = TRUE)
  n_treated <- sum(dt[[treatment]] == 1, na.rm = TRUE)
  n_censored <- if (!is.null(censor)) sum(dt[[censor]] == 1, na.rm = TRUE) else 0L

  # Build settings
  settings <- list(
    id = id,
    period = period,
    treatment = treatment,
    outcome = outcome,
    eligible = eligible,
    censor = censor,
    covariates = covariates,
    baseline_covariates = baseline_covariates,
    estimand = estimand,
    prefix = prefix
  )

  # Create emulate object
  obj <- new_emulate(dt, settings)
  obj$state$prepared <- TRUE

  # Display summary
  message("emulate_prepare - Data Preparation")
  message(strrep("-", 50))
  message("Estimand:      ", estimand)
  message("Observations:  ", format(n_obs, big.mark = ","))
  message("Individuals:   ", format(n_ids, big.mark = ","))
  message("Period range:  ", period_range[1], " - ", period_range[2])
  message("Eligible obs:  ", format(n_eligible, big.mark = ","))
  message("Treated obs:   ", format(n_treated, big.mark = ","))
  message("Events:        ", format(n_events, big.mark = ","))
  message(strrep("-", 50))

  invisible(obj)
}
